name: gae-ci-cd
on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
  
jobs:
   build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
   deploy:
    if: github.ref == 'refs/heads/main'
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      #Checking if the app build successfully
      - name: npm install
        run: npm run

      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY}}
          version: v1
